const products = [
    {
        id: 1,
        img: "./scr/img/Criativo do HUB Modal/Produtos/Moda 1/Moldura das roupas - 1.png",
        nameItem: "Nome do vestuario",
        description: "Adicione um pouco de energia ao seu guarda-roupa de inverno com esta jaqueta vibrante...",
        value: 100,
        addCart: "Adicionar ao carrinho",
        addFavorit: "Favorito",
        cart: "Comprar",
        tag: ["Camisetas"],
    },
    {
        id: 2,
        img: "./scr/img/Criativo do HUB Modal/Produtos/Moda 1/Moldura das roupas - 1.png",
        nameItem: "Nome do vestuario",
        description: "Adicione um pouco de energia ao seu guarda-roupa de inverno com esta jaqueta vibrante...",
        value: 100,
        addCart: "Adicionar ao carrinho",
        addFavorit: "Favorito",
        cart: "Comprar",
        tag: ["Camisetas"],
    },
    {
        id: 3,
        img: "./scr/img/Criativo do HUB Modal/Produtos/Moda 1/Moldura das roupas - 1.png",
        nameItem: "Nome do vestuario",
        description: "Adicione um pouco de energia ao seu guarda-roupa de inverno com esta jaqueta vibrante...",
        value: 100,
        addCart: "Adicionar ao carrinho",
        addFavorit: "Favorito",
        cart: "Comprar",
        tag: ["Camisetas"],
    },
    {
        id: 4,
        img: "./scr/img/Criativo do HUB Modal/Produtos/Moda 1/Moldura das roupas - 1.png",
        nameItem: "Nome do vestuario",
        description: "Adicione um pouco de energia ao seu guarda-roupa de inverno com esta jaqueta vibrante...",
        value: 100,
        addCart: "Adicionar ao carrinho",
        addFavorit: "Favorito",
        cart: "Comprar",
        tag: ["Camisetas"],
    },
    {
        id: 5,
        img: "./scr/img/Criativo do HUB Modal/Produtos/Moda 1/Moldura das roupas - 1.png",
        nameItem: "Nome do vestuario",
        description: "Adicione um pouco de energia ao seu guarda-roupa de inverno com esta jaqueta vibrante...",
        value: 100,
        addCart: "Adicionar ao carrinho",
        addFavorit: "Favorito",
        cart: "Comprar",
        tag: ["Camisetas"],
    },
    {
        id: 6,
        img: "./scr/img/Criativo do HUB Modal/Produtos/Moda 1/Moldura das roupas - 1.png",
        nameItem: "Nome do vestuario",
        description: "Adicione um pouco de energia ao seu guarda-roupa de inverno com esta jaqueta vibrante...",
        value: 100,
        addCart: "Adicionar ao carrinho",
        addFavorit: "Favorito",
        cart: "Comprar",
        tag: ["Camisetas"],
    },
    {
        id: 7,
        img: "./scr/img/Criativo do HUB Modal/Produtos/Moda 1/Moldura das roupas - 1.png",
        nameItem: "Nome do vestuario",
        description: "Adicione um pouco de energia ao seu guarda-roupa de inverno com esta jaqueta vibrante...",
        value: 100,
        addCart: "Adicionar ao carrinho",
        addFavorit: "Favorito",
        cart: "Comprar",
        tag: ["Camisetas"],
    },
    {
        id: 8,
        img: "./scr/img/Criativo do HUB Modal/Produtos/Moda 1/Moldura das roupas - 1.png",
        nameItem: "Nome do vestuario",
        description: "Adicione um pouco de energia ao seu guarda-roupa de inverno com esta jaqueta vibrante...",
        value: 100,
        addCart: "Adicionar ao carrinho",
        addFavorit: "Favorito",
        cart: "Comprar",
        tag: ["Camisetas"],
    }
]